### ISSUE TITLE
No error message displayed on login

### ISSUE THREAD

**Issue by kumarkishore1001** [osrmt/osrmt#21]
**Description**
Now for any incorrect combination or without value, when user try to click on 'Ok', it do not show any error message.

**Steps to Reproduce**

1. Reach to login page
2. Try all invalid combinations. No error messages are displayed

![Screenshot 2019-04-28 at 12 06 33 AM](https://user-images.githubusercontent.com/35497153/56853747-a39cc480-6949-11e9-9cc9-9c5617e2fbd8.png)

**Comment by rpandhurkar** [comment]
![image](https://user-images.githubusercontent.com/48993334/56857437-25f9a880-698b-11e9-8198-f9901ac06241.png)
![image](https://user-images.githubusercontent.com/48993334/56857440-390c7880-698b-11e9-9000-49820d55affd.png)

**Comment by rpandhurkar** [comment]
Its working for me, kindly refer attached screenshot

**Comment by kumarkishore1001** [comment]
> Its working for me, kindly refer attached screenshot
@rpandhurkar I have already attached the screenshot with the issue but you can't see the error message cuz it is not there. Please refer to the attached video

https://screencast.com/t/wOWTpHJfGPv

**Comment by rpandhurkar** [comment]
Yes, Its working on windows but there is some issue with MAC, working on the same.

**Comment by rpandhurkar** [comment]
Hi Kishore
Can u change the resolution such as 1366*768 or less and let me know if you able to see error message

**Comment by rpandhurkar** [comment]
It was an resolution issue, I fixed this issue and tested it successfully on both MAC and windows.

**Comment by kumarkishore1001** [comment]
Closing this issue as it is working alright.
Verified in 1.8 release
