### ISSUE TITLE
Reports not getting saved in correct format

### ISSUE THREAD

**Issue by kumarkishore1001** [osrmt/osrmt#41]
**Description**
Reports not getting saved in correct format.
It shows PDF and HTML but can't able to see the same format.
**Screenshot**
https://screencast.com/t/vjdjctbiqE0K

**Comment by mschmidtesd** [comment]
The reports subdirectory contains template or source files for available reports, not the results. When running the report tool a dialog queries the user to enter a path to the resulting report file, which defaults to something like temp/~[0-9]*osrmt.htm or .pdf.

Look in <osmrt_dir>\temp for your report results.

**Comment by rquarry** [comment]
I just tested this, @mschmidtesd is correct. The system clearly queries the user for a specific file path that defaults to <osmrt_dir>\temp. I was able to generate some test reports to this folder path. I believe this issue can be closed.

![Screenshot from 2020-04-26 07-27-34](https://user-images.githubusercontent.com/54045716/80306399-145f0280-8791-11ea-9c3a-9ac9cce3533e.png)

**Comment by ZoranPandovski** [comment]
Thanks, @rquarry. Since you are active on this project lately feel free to send me an email so I can include you on the slack channel.

**Comment by rquarry** [comment]
@ZoranPandovski , I spent some time trying to locate your E-mail address to send a message and didn't come up with anything.

**Comment by ZoranPandovski** [comment]
Send it to zoran.pandovski@gmail.com
